jobs:
  build_and_deploy_gke:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          command: |
            ./gradlew build
      - run:
          command: |
            pwd
            ls -la
            echo ${HOME}
      - cloudrun/init
      - cloudrun/create_gke_cluster:
          cluster-name: 'example-cluster-${CIRCLE_BUILD_NUM}'
          enable-stackdriver-kubernetes: true
          machine-type: e2-micro
          scopes: cloud-platform
          zone: us-east1-c
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
      - cloudrun/deploy:
          cluster: 'example-cluster-${CIRCLE_BUILD_NUM}'
          cluster-location: us-east1
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
          platform: gke
          service-name: 'example-service-${CIRCLE_BUILD_NUM}'
orbs:
  gradle: circleci/gradle@2.2.0
  cloudrun: circleci/gcp-cloud-run@1.0.2
version: 2.1
workflows:
  build_and_deploy_to_gke_workflow:
    jobs:
      - build_and_deploy_gke